# -*- coding: utf-8 -*-
"""aspect_based_sentiment_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f79PbrQ8u6dHspgLLG52PjG7LoqmRx26
"""

!pip install pyabsa

from pyabsa.functional import ATEPCModelList

import pandas as pd
#data = pd.read_csv('reviews.csv', delimiter='\t')
#data.head(5)
#data['review_ID'] = data.index
#data

from pyabsa import available_checkpoints
checkpoint_map = available_checkpoints()

#data['Review'].head(5)

from pyabsa.functional import ABSADatasetList
from pyabsa.functional import ATEPCCheckpointManager

#examples = data['Review'].tolist()

#inference_source = examples
#aspect_extractor = ATEPCCheckpointManager.get_aspect_extractor(checkpoint='multilingual')
#atepc_result = aspect_extractor.extract_aspect(inference_source=inference_source,
#                                               save_result=True,
#                                               print_result=False,  # print the result
#                                               pred_sentiment=True,  # Predict the sentiment of extracted aspect terms
#                                               )

#import pandas as pd
#df = pd.read_json('atepc_inference.result.json')

#df.tail(5)

#df['review_ID'] = df.index
#df = pd.merge(df, data, on = 'review_ID')
#df.tail(5)

#df1 = df.drop(columns = ['sentence', 'IOB', 'tokens', 'probs', 'confidence', 'position', 'RatingValue', 'DatePublished', 'Review'], axis =1)
#df1

#df2 = df1.apply(pd.Series.explode)

#df2.reset_index(drop = True, inplace = True)
#df2.tail(5)

data = pd.read_csv('reviews.csv', delimiter='\t')
#data.head(5)
data['review_ID'] = data.index
examples = data['Review'].tolist()
def asba(examples):
  inference_source = examples
  aspect_extractor = ATEPCCheckpointManager.get_aspect_extractor(checkpoint='multilingual')
  atepc_result = aspect_extractor.extract_aspect(inference_source=inference_source,
                                               save_result=True,
                                               print_result=False,  # print the result
                                               pred_sentiment=True,  # Predict the sentiment of extracted aspect terms
                                               )
  df = pd.read_json('atepc_inference.result.json')
  df['review_ID'] = df.index
  df = pd.merge(df, data, on = 'review_ID')
  df = df.rename(columns={'aspect': 'Aspect', 'sentiment': 'Sentiment'})
  df1 = df.drop(columns = ['sentence', 'IOB', 'tokens', 'probs', 'confidence', 
                           'position', 'RatingValue', 'DatePublished', 'Review'], axis =1)
  df2 = df1.apply(pd.Series.explode)
  df2.reset_index(drop = True, inplace = True)
  return df2

asba_df = asba(examples)
asba_df

